import type { Metadata } from "next";
import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import Link from "next/link";
import { NavBarSide } from "../components/navbar/navbar-side";
import TopBar from "../components/navbarTop/navBarTop";
import { BreadCrumb } from "../components/navbarTop/bread-crumb";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopBar />
      <NavBarSide>
        <section className="px-7 flex gap-7 flex-col overflow-hidden w-full">
          <div className=" pt-6">
            {/* breadcrumb */}
            <BreadCrumb />
            {/* text */}
            <div className="flex gap-1 mt-7">
              <span>
                <CalendarMonthIcon className="text-aquamarine" />
              </span>
              <h1 className="text-lg font-light text-steelGray">Cronograma</h1>
            </div>
            <hr className="bg-mercuryGray h-[1px] my-2 opacity-30" />
            <p>
              Aqui você pode acompanhar os resultados dos seus projetos.
              <Link
                className="text-aquamarine font-bold ml-1"
                href="/saiba-mais"
              >
                Saiba mais
              </Link>
            </p>
          </div>
          {children}
        </section>
      </NavBarSide>
    </>
  );
}
