import { ProjetosScreen } from "./page.client";

function getData() {
  return [
    {
      data_conclusao: "01/10/2023",
      data_etapa: "01/10/2023",
      id_projeto: 6473,
      identificador_etapa: "X",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "02/08/2023",
      data_etapa: "01/13/2023",
      id_projeto: 6473,
      identificador_etapa: "A",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "02/01/2023",
      data_etapa: "01/13/2023",
      id_projeto: 6473,
      identificador_etapa: "B",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "02/28/2023",
      data_etapa: "01/18/2023",
      id_projeto: 6473,
      identificador_etapa: "C",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "03/02/2023",
      data_etapa: "02/16/2023",
      id_projeto: 6473,
      identificador_etapa: "D",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "03/15/2023",
      data_etapa: "02/28/2023",
      id_projeto: 6473,
      identificador_etapa: "E",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "03/15/2023",
      data_etapa: "03/01/2023",
      id_projeto: 6473,
      identificador_etapa: "F",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "03/15/2023",
      data_etapa: "03/08/2023",
      id_projeto: 6473,
      identificador_etapa: "G",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "05/12/2023",
      data_etapa: "04/05/2023",
      id_projeto: 6473,
      identificador_etapa: "H",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "04/05/2023",
      data_etapa: "04/05/2023",
      id_projeto: 6473,
      identificador_etapa: "I",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "05/19/2023",
      data_etapa: "04/05/2023",
      id_projeto: 6473,
      identificador_etapa: "J",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "05/05/2023",
      data_etapa: "04/24/2023",
      id_projeto: 6473,
      identificador_etapa: "K",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "05/31/2023",
      data_etapa: "05/26/2023",
      id_projeto: 6473,
      identificador_etapa: "L",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "05/26/2023",
      data_etapa: "05/26/2023",
      id_projeto: 6473,
      identificador_etapa: "M",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "06/21/2023",
      data_etapa: "06/14/2023",
      id_projeto: 6473,
      identificador_etapa: "N",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "06/26/2023",
      data_etapa: "06/14/2023",
      id_projeto: 6473,
      identificador_etapa: "O",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "",
      data_etapa: "12/31/2023",
      id_projeto: 6473,
      identificador_etapa: "Z",
      nome_projeto: "M.E - Excelência da Entrega",
      ordem_projeto: "1",
    },
    {
      data_conclusao: "09/01/2022",
      data_etapa: "05/31/2023",
      id_projeto: 6475,
      identificador_etapa: "X",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "09/22/2022",
      data_etapa: "09/20/2022",
      id_projeto: 6475,
      identificador_etapa: "A",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/15/2022",
      data_etapa: "09/21/2022",
      id_projeto: 6475,
      identificador_etapa: "B",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/11/2022",
      data_etapa: "09/28/2022",
      id_projeto: 6475,
      identificador_etapa: "C",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/11/2022",
      data_etapa: "10/10/2022",
      id_projeto: 6475,
      identificador_etapa: "D",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/14/2022",
      data_etapa: "10/13/2022",
      id_projeto: 6475,
      identificador_etapa: "E",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/13/2022",
      data_etapa: "10/13/2022",
      id_projeto: 6475,
      identificador_etapa: "F",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/28/2022",
      data_etapa: "10/14/2022",
      id_projeto: 6475,
      identificador_etapa: "G",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/21/2022",
      data_etapa: "10/17/2022",
      id_projeto: 6475,
      identificador_etapa: "H",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "10/25/2022",
      data_etapa: "10/25/2022",
      id_projeto: 6475,
      identificador_etapa: "I",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "02/08/2023",
      data_etapa: "10/31/2022",
      id_projeto: 6475,
      identificador_etapa: "J",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "02/08/2023",
      data_etapa: "11/01/2022",
      id_projeto: 6475,
      identificador_etapa: "K",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "11/10/2022",
      data_etapa: "11/07/2022",
      id_projeto: 6475,
      identificador_etapa: "L",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "11/18/2022",
      data_etapa: "11/18/2022",
      id_projeto: 6475,
      identificador_etapa: "M",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "12/05/2022",
      data_etapa: "11/28/2022",
      id_projeto: 6475,
      identificador_etapa: "N",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "01/07/2023",
      data_etapa: "01/04/2023",
      id_projeto: 6475,
      identificador_etapa: "O",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "02/14/2023",
      data_etapa: "02/08/2023",
      id_projeto: 6475,
      identificador_etapa: "P",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "02/15/2023",
      data_etapa: "02/15/2023",
      id_projeto: 6475,
      identificador_etapa: "Q",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "02/20/2023",
      data_etapa: "02/16/2023",
      id_projeto: 6475,
      identificador_etapa: "R",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "03/08/2023",
      data_etapa: "02/21/2023",
      id_projeto: 6475,
      identificador_etapa: "S",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "04/30/2023",
      data_etapa: "04/26/2023",
      id_projeto: 6475,
      identificador_etapa: "T",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "08/07/2023",
      data_etapa: "04/26/2023",
      id_projeto: 6475,
      identificador_etapa: "U",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "08/14/2023",
      data_etapa: "04/26/2023",
      id_projeto: 6475,
      identificador_etapa: "V",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "12/15/2023",
      data_etapa: "11/28/2023",
      id_projeto: 6475,
      identificador_etapa: "W",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "12/15/2023",
      data_etapa: "12/31/2023",
      id_projeto: 6475,
      identificador_etapa: "Z",
      nome_projeto: "M.E - Telemetria",
      ordem_projeto: "3",
    },
    {
      data_conclusao: "02/08/2023",
      data_etapa: "02/08/2023",
      id_projeto: 6476,
      identificador_etapa: "X",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "02/15/2023",
      data_etapa: "02/08/2023",
      id_projeto: 6476,
      identificador_etapa: "A",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "05/05/2023",
      data_etapa: "04/03/2023",
      id_projeto: 6476,
      identificador_etapa: "B",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "04/17/2023",
      data_etapa: "04/12/2023",
      id_projeto: 6476,
      identificador_etapa: "C",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "04/13/2023",
      data_etapa: "04/12/2023",
      id_projeto: 6476,
      identificador_etapa: "D",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "05/17/2023",
      data_etapa: "04/13/2023",
      id_projeto: 6476,
      identificador_etapa: "E",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "04/17/2023",
      data_etapa: "04/17/2023",
      id_projeto: 6476,
      identificador_etapa: "F",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "04/19/2023",
      data_etapa: "04/19/2023",
      id_projeto: 6476,
      identificador_etapa: "G",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "04/26/2023",
      data_etapa: "04/19/2023",
      id_projeto: 6476,
      identificador_etapa: "H",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "05/05/2023",
      data_etapa: "05/04/2023",
      id_projeto: 6476,
      identificador_etapa: "I",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "05/19/2023",
      data_etapa: "05/17/2023",
      id_projeto: 6476,
      identificador_etapa: "J",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "08/07/2023",
      data_etapa: "06/19/2023",
      id_projeto: 6476,
      identificador_etapa: "K",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "06/20/2023",
      data_etapa: "06/20/2023",
      id_projeto: 6476,
      identificador_etapa: "L",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "06/20/2023",
      data_etapa: "06/20/2023",
      id_projeto: 6476,
      identificador_etapa: "M",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "06/20/2023",
      data_etapa: "06/20/2023",
      id_projeto: 6476,
      identificador_etapa: "N",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "11/16/2023",
      data_etapa: "08/29/2023",
      id_projeto: 6476,
      identificador_etapa: "O",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "",
      data_etapa: "12/31/2023",
      id_projeto: 6476,
      identificador_etapa: "P",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "",
      data_etapa: "12/31/2023",
      id_projeto: 6476,
      identificador_etapa: "Z",
      nome_projeto: "M.E - Revisão da malha logística",
      ordem_projeto: "4",
    },
    {
      data_conclusao: "08/30/2022",
      data_etapa: "08/30/2022",
      id_projeto: 6717,
      identificador_etapa: "X",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "09/16/2022",
      data_etapa: "08/16/2022",
      id_projeto: 6717,
      identificador_etapa: "A",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "09/27/2022",
      data_etapa: "09/08/2022",
      id_projeto: 6717,
      identificador_etapa: "B",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "10/10/2022",
      data_etapa: "09/08/2022",
      id_projeto: 6717,
      identificador_etapa: "C",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "10/05/2022",
      data_etapa: "10/03/2022",
      id_projeto: 6717,
      identificador_etapa: "D",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "10/07/2022",
      data_etapa: "10/03/2022",
      id_projeto: 6717,
      identificador_etapa: "E",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "10/14/2022",
      data_etapa: "10/10/2022",
      id_projeto: 6717,
      identificador_etapa: "F",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "12/30/2022",
      data_etapa: "10/10/2022",
      id_projeto: 6717,
      identificador_etapa: "G",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "10/27/2022",
      data_etapa: "10/13/2022",
      id_projeto: 6717,
      identificador_etapa: "H",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "10/21/2022",
      data_etapa: "10/17/2022",
      id_projeto: 6717,
      identificador_etapa: "I",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "01/06/2023",
      data_etapa: "01/04/2023",
      id_projeto: 6717,
      identificador_etapa: "J",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "01/09/2023",
      data_etapa: "01/04/2023",
      id_projeto: 6717,
      identificador_etapa: "K",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "03/15/2023",
      data_etapa: "01/13/2023",
      id_projeto: 6717,
      identificador_etapa: "L",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "02/10/2023",
      data_etapa: "02/01/2023",
      id_projeto: 6717,
      identificador_etapa: "M",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "03/21/2023",
      data_etapa: "02/08/2023",
      id_projeto: 6717,
      identificador_etapa: "N",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "03/17/2023",
      data_etapa: "03/10/2023",
      id_projeto: 6717,
      identificador_etapa: "O",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "03/31/2023",
      data_etapa: "03/25/2023",
      id_projeto: 6717,
      identificador_etapa: "P",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "04/06/2023",
      data_etapa: "03/29/2023",
      id_projeto: 6717,
      identificador_etapa: "Q",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "04/06/2023",
      data_etapa: "04/05/2023",
      id_projeto: 6717,
      identificador_etapa: "R",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "04/10/2023",
      data_etapa: "04/06/2023",
      id_projeto: 6717,
      identificador_etapa: "S",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "04/19/2023",
      data_etapa: "04/10/2023",
      id_projeto: 6717,
      identificador_etapa: "T",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "04/14/2023",
      data_etapa: "04/13/2023",
      id_projeto: 6717,
      identificador_etapa: "U",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "05/29/2023",
      data_etapa: "05/25/2023",
      id_projeto: 6717,
      identificador_etapa: "V",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "05/25/2023",
      data_etapa: "05/25/2023",
      id_projeto: 6717,
      identificador_etapa: "W",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "05/29/2023",
      data_etapa: "05/25/2023",
      id_projeto: 6717,
      identificador_etapa: "Y",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "06/02/2023",
      data_etapa: "06/01/2023",
      id_projeto: 6717,
      identificador_etapa: "AA",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "09/19/2023",
      data_etapa: "06/16/2023",
      id_projeto: 6717,
      identificador_etapa: "AB",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "11/16/2023",
      data_etapa: "11/16/2023",
      id_projeto: 6717,
      identificador_etapa: "AC",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "12/15/2023",
      data_etapa: "12/15/2023",
      id_projeto: 6717,
      identificador_etapa: "AD",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
    {
      data_conclusao: "",
      data_etapa: "11/30/2023",
      id_projeto: 6717,
      identificador_etapa: "Z",
      nome_projeto: "M.E - Processo de Monitoramento-",
      ordem_projeto: "5",
    },
  ];
}

export default async function Projetos() {
  const data = getData();

  return (
    <div>
      <ProjetosScreen data={data} />
    </div>
  );
}
